### ISSUE TITLE
Confusion in Double Elimination Pairing

### ISSUE THREAD

**Issue by toriqahmads** [slashinfty/tournament-pairings#1]
Hi, thank you for creating this library, this is very useful library. I really appreciate it.

After trying this library, I got some confusion in double elimination pairing.
1. How to know which match is Upper or Lower bracket?
2. How to know a grand final for Upper and Lower bracket match?
3. How to split a seeds into Upper and Lower bracket for first round, so is not only started at Upper bracket in first round

Thank you so much

**Comment by slashinfty** [comment]
Hello, and thank you!

To be clear, double elimination pairings create a winner's bracket and a loser's bracket.

1. The last round of the winner's bracket contains a single match with no `win` or `loss` object (what would be the path for the winner and loser of the match). So, all rounds before and including that round are in the winner's bracket, and all subsequent rounds are in the loser's bracket. If you look [here](https://github.com/slashinfty/tournament-pairings/blob/b9d5ad72abce061158ec9b2467c1a49d34ab9771/test/DoubleElimination.test.ts#L6-L107), rounds 1 through 4 are the winner's bracket, while rounds 5 through 8 are the loser's bracket.
2. The "grand final" is the last round of the winner's bracket, which is described above.
3. The only way to enter the "lower bracket" (loser's bracket) is to lose a match in the "upper bracket" (winner's bracket). There is no way to start with a loss, so there is no way to start in the loser's bracket.

I am going to close this issue. If you have further questions about this, please join the [Discord](https://discord.gg/Q8t9gcZ77s).
