### ISSUE TITLE
Score vs. Rating on Swiss Pairing

### ISSUE THREAD

**Issue by ianpaschal** [slashinfty/tournament-pairings#3]
Hi,

I'm working on a project for wargaming tournaments and I'm interested to see if I can toss out all my pairing logic in favor of using yours. But this raises a question about Swiss pairing (the most commonly used in my region/community):

What is the difference between score and rating? It's not clear to me from the documentation and what they represent. I assume score is essentially the same as ranking (e.g. highest score -> lowest score matches highest rank -> lowest rank) for the purposes of pairing? But I'm not sure what rating is or how it factors in.

Additionally, I'm curious if you have an idea (in broad strokes) how to handle a tiered scoring system. For example, most Swiss pairing approaches in my community use # of wins as the first level of comparison, then # of points scored as the next tie breaker, and so and and so forth with other factors in each match. I can imagine one solution might be to create a weighted score where the primary factor counts for, say, 1000000 units of score per win, points count for 1000 units of score, etc. But this feels hacky compared to a cascading set of comparisons. Thoughts?

Thanks!

**Comment by slashinfty** [comment]
Score has to do with matches won, while rating is usually one of two things: a measure of skill, like in chess, or a seeding, like an initial rank. 

Tiebreakers aren't considered when it comes to pairing. I think that's getting a little too granular. However, if you want something that does standings with tiebreakers, my other package ([tournament-organizer](https://github.com/slashinfty/tournament-organizer)), can do that.

**Comment by ianpaschal** [comment]
Interesting. Thanks for your response!

To me, it seems that "tie breakers" or at least a granular ranking is needed to properly do Swiss pairing. For example, after game 1, 50% of players will have a "score" of 1, but if you have 40 players, you don't want to pair Rank 1 against Rank 19. Instead you want 1 vs 2, 3 vs 4, and so on.

I guess this is what the rating is for? To sort within the "score" groups?

**Comment by slashinfty** [comment]
Tiebreakers really shouldn't be relevant until determining placing at the end of a tournament. Swiss is just about making sure players who have won 3 games don't play those who haven't won any. It's about similar strength *and* performance, not necessarily equal.

Regarding your example: after round 1, aren't all tiebreakers essentially equal for players with the same score?

If your concern is two players with the same score having radically different skill levels, you either need to run separate tournaments for different skill levels, or assign a rating to players so players of similar skill are more likely to play each other. The default for Swiss is consider only performance - all players with the same score are performing similarly, so they must be of similar strength.

If you'd like to continue the discussion, you're welcome to join my Discord (link in the readme). However, I do not intend to make any changes to the pairing algorithm based on this issue.
